Hw4
svp8/tinkoff pull request #5
Opened 2023-10-28 12:20 UTC by svp8

2023-11-01 08:40 UTC, balakhontsevaa commented on src/main/java/edu/hw4/Animal.java
> +    public static final int FOURPAWS = 4;
Имена констант в SNACK_CASE, в твоем случае вот так, например:
`public static final int FOUR_PAWS = 4;`

2023-11-01 08:40 UTC, balakhontsevaa commented on src/main/java/edu/hw4/Animal.java
> +    enum Type {
enum лучше выносить в отдельные файлы - single responsibility принцип

2023-11-01 08:41 UTC, balakhontsevaa commented on src/main/java/edu/hw4/Tasks11to20.java
> +//            .collect(Collectors.toMap(Animal::type, animal -> animal.bites() ? 1 : 0, Integer::sum))
если комментарии не нужны - лучше удалить)

2023-11-01 08:42 UTC, balakhontsevaa commented on src/main/java/edu/hw4/Tasks11to20.java
> +            .filter(animal -> animal.type().equals(Animal.Type.SPIDER) && animal.bites()).count();
обычно приятно сравнивать какие-то известные данные с теми, что пришли к нам или же были посчитаны

2023-11-01 08:42 UTC, balakhontsevaa commented on src/main/java/edu/hw4/Tasks11to20.java
> +//        return animals.stream().collect(Collectors
такой же момент. Если не нужно - удали

2023-11-01 08:45 UTC, balakhontsevaa commented on src/main/java/edu/hw4/Tasks1to10.java
> +        return animals.stream().filter(animal -> animal.paws() != animal.age()).toList();
Смотри, что касается форматирования стримов, принято каждый метод стрима располагать с новой строки, вот так, например:
```
.stream()
.sorted(Comparator.comparingInt(Animal::age).reversed())
.limit(k)
.toList().getLast();
```
Поправь в остальных местах, пожалуйста.

2023-11-01 08:55 UTC, balakhontsevaa commented on src/test/java/edu/hw4/Tasks11to20Test.java
> +        List<Animal> expected = List.of(
Используй, пожалуйста, шаблон для тестов. Можно given-when-then или aaa, особой разницы нет, это одно и то же)
Вообще вот эта статья полезная - https://habr.com/ru/articles/554808/, можешь просмотреть, если время будет.

2023-11-03 13:59 UTC, nexen505 commented on src/main/java/edu/hw4/Tasks11to20.java
> +            .filter(animal -> animal.type().equals(Animal.Type.SPIDER) && animal.bites()).count();
Я думаю, тут это некритично: если тип животного будет `null`, то много другого кода и так сломается :)

2023-11-03 14:11 UTC, nexen505 requested changes

2023-11-03 14:11 UTC, nexen505 commented on src/main/java/edu/hw4/Tasks11to20.java
> +    public static Integer sumWeightWithAgeFromKtoL(List<Animal> animals, int k, int l) {
Проблема: по заданию тут нужно посчитать суммарный вес для каждого вида, а не общий.

> Найти суммарный вес животных каждого вида, которым от k до l лет -> Map<Animal.Type, Integer>

Предложение: исправить реализацию в соответствии с заданием.

2023-11-07 18:42 UTC, merged